gg:
    jte:
        development-mode: true
spring:
    application:
        name: demo-crud
    datasource:
        # url: jdbc:h2:mem:demo-crud -> conectar via jdbc:h2:mem:demo-crud
        url: jdbc:h2:file:./data/mydb
        driver-class-name: org.h2.Driver
        username: sa
        password: sa
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: update
        generate-ddl: true
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    sql:
        init:
            mode: always

