spring:
    application:
        name: ifba

    datasource:
        url: jdbc:sqlserver://localhost:1433;databaseName=nome_do_seu_banco
        username: localhost/Jande
        password: 
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
